// Renders every Fire Night sprite of the play screen from one place:
//   node tools/art/fire_night/render.js      (needs Playwright's Chromium, as a global npm module)
// To swap in new art, change the drawing in mock.js / lib2.js / mam.js / iss.js / sprites.js (the JOBS
// list names every sprite, its cell, anchor and scale) and re-run this, then
// `godot --headless --path game --import`. It writes the PNGs to game/art/fire/ and their cells
// (size, anchor, drawn bounds) to game/scripts/art/fire_cells.gd, which FireSkin reads, so nothing else
// needs editing. mock.html draws the mockup itself, for comparison.
const path = require('path'), fs = require('fs');
const { chromium } = require(require('child_process').execSync('npm root -g').toString().trim() + '/playwright');
(async () => {
  const root = path.resolve(__dirname, '../../../game');
  const out = path.join(root, 'art/fire');
  fs.mkdirSync(out, { recursive: true });
  const b = await chromium.launch();
  const p = await b.newPage();
  await p.goto('file://' + path.resolve(__dirname, 'sprites.html'));
  const man = await p.evaluate(() => manifest());
  const cells = [];
  for (const s of man.sprites) {
    const r = await p.evaluate(n => renderJob(n), s.name);
    fs.writeFileSync(path.join(out, s.name + '.png'), Buffer.from(r.url.split(',')[1], 'base64'));
    const v = a => a.map(x => Number.isInteger(x) ? x.toFixed(1) : String(x)).join(', ');
    cells.push(`\t"${s.name}": [Vector2(${v([s.w, s.h])}), Vector2(${v([s.ax, s.ay])}), Rect2(${v([r.bounds[0], r.bounds[1], r.bounds[2] - r.bounds[0], r.bounds[3] - r.bounds[1]])})],`);
  }
  const gd = `class_name FireCells
extends RefCounted
## Generated by tools/art/fire_night/render.js — do not edit; re-run it after changing the art.
## Every Fire Night sprite in res://art/fire/: [cell size, anchor, drawn bounds relative to the anchor],
## all in the mockup's reference pixels (the PNGs are baked at a multiple of that).

const FIG_H := ${man.fig_h}.0   ## figures are drawn this tall in their cells
const CELLS := {
${cells.join('\n')}
}
`;
  fs.writeFileSync(path.join(root, 'scripts/art/fire_cells.gd'), gd);
  console.log('rendered', man.sprites.length, 'sprites to', out);
  await b.close();
})();
