"""Bakes every pose of the two characters into game/art/px/figures/ (1x PNGs) and writes their cells
to game/scripts/art/figure_cells.gd, which FigureSprites reads:
    python3 tools/art/pixel/bake_figures.py
Names: [big_]mamuthone_<fleece>_<pose>, [big_]issohadore_<pose>. Change the drawing in figures.py,
re-run this, then `godot --headless --path game --import`."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import figures  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../game"))
OUT = os.path.join(ROOT, "art/px/figures")


def main():
    os.makedirs(OUT, exist_ok=True)
    cells = []
    for size in ("field", "big"):
        pre = "" if size == "field" else "big_"
        jobs = []
        for fl in ("black", "dark_brown"):
            for pose in figures.MAM_POSES:
                jobs.append((f"{pre}mamuthone_{fl}_{pose}", lambda p=pose, f=fl: figures.mamuthone(p, fleece=f, size=size)))
        for pose in figures.ISS_POSES:
            jobs.append((f"{pre}issohadore_{pose}", lambda p=pose: figures.issohadore(p, size=size)))
        fx, fy = figures.FEET[size]
        for name, fn in jobs:
            cv = fn()
            cv.save(os.path.join(OUT, name + ".png"))
            x0, y0, x1, y1 = cv.bbox()
            cells.append(f'\t"{name}": [Vector2({cv.w}, {cv.h}), Vector2({fx}, {fy}), Rect2({x0 - fx}, {y0 - fy}, {x1 - x0}, {y1 - y0})],')
    gd = """class_name FigureCells
extends RefCounted
## Generated by tools/art/pixel/bake_figures.py - do not edit; re-run it after changing figures.py.
## Every character sprite in res://art/px/figures/: [cell size, feet anchor, drawn bounds relative to
## the feet], in art pixels (1x).

const CELLS := {
%s
}
""" % "\n".join(cells)
    with open(os.path.join(ROOT, "scripts/art/figure_cells.gd"), "w") as f:
        f.write(gd)
    print("baked", len(cells), "figures to", OUT)


if __name__ == "__main__":
    main()
