"""Writes game/scripts/art/pixel_palette.gd from palette.py, so Godot code draws with the same colours:
    python3 tools/art/pixel/gen_palette_gd.py"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from palette import RAMPS  # noqa: E402

root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../game"))
lines = [
    "class_name PixelPalette",
    "extends RefCounted",
    "## Generated by tools/art/pixel/gen_palette_gd.py from tools/art/pixel/palette.py - do not edit.",
    "## The \"Bonfire Night\" pixel palette (docs/art-style.md): ramps dark to light, e.g. FIRE[5].",
    "",
]
for name, cols in RAMPS.items():
    lines.append("const %s: Array[Color] = [%s]" % (name, ", ".join('Color("%s")' % c for c in cols)))
lines += [
    "",
    "## Art pixels per base-screen pixel: art is authored at 240 x 480 for the 720 x 1440 base screen.",
    "const PX := 3.0",
    "",
]
with open(os.path.join(root, "scripts/art/pixel_palette.gd"), "w") as f:
    f.write("\n".join(lines))
print("wrote pixel_palette.gd")
