class_name FigureCells
extends RefCounted
## Generated by tools/art/pixel/bake_figures.py - do not edit; re-run it after changing figures.py.
## Every character sprite in res://art/px/figures/: [cell size, feet anchor, drawn bounds relative to
## the feet], in art pixels (1x).

const CELLS := {
	"mamuthone_black_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -65, 44, 66)],
	"mamuthone_black_crouch": [Vector2(88, 84), Vector2(44, 80), Rect2(-25, -61, 46, 62)],
	"mamuthone_black_air": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -66, 46, 65)],
	"mamuthone_black_land": [Vector2(88, 84), Vector2(44, 80), Rect2(-26, -60, 49, 61)],
	"mamuthone_dark_brown_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -65, 44, 66)],
	"mamuthone_dark_brown_crouch": [Vector2(88, 84), Vector2(44, 80), Rect2(-25, -61, 46, 62)],
	"mamuthone_dark_brown_air": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -66, 46, 65)],
	"mamuthone_dark_brown_land": [Vector2(88, 84), Vector2(44, 80), Rect2(-26, -60, 49, 61)],
	"issohadore_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-14, -70, 30, 71)],
	"issohadore_throw": [Vector2(88, 84), Vector2(44, 80), Rect2(-14, -80, 29, 81)],
	"big_mamuthone_black_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -103, 68, 104)],
	"big_mamuthone_black_crouch": [Vector2(140, 132), Vector2(70, 127), Rect2(-39, -97, 71, 98)],
	"big_mamuthone_black_air": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -105, 70, 103)],
	"big_mamuthone_black_land": [Vector2(140, 132), Vector2(70, 127), Rect2(-41, -95, 76, 96)],
	"big_mamuthone_dark_brown_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -103, 68, 104)],
	"big_mamuthone_dark_brown_crouch": [Vector2(140, 132), Vector2(70, 127), Rect2(-39, -97, 71, 98)],
	"big_mamuthone_dark_brown_air": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -105, 70, 103)],
	"big_mamuthone_dark_brown_land": [Vector2(140, 132), Vector2(70, 127), Rect2(-41, -95, 76, 96)],
	"big_issohadore_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-22, -112, 47, 112)],
	"big_issohadore_throw": [Vector2(140, 132), Vector2(70, 127), Rect2(-22, -127, 44, 127)],
}
