class_name FigureCells
extends RefCounted
## Generated by tools/art/pixel/bake_figures.py - do not edit; re-run it after changing figures.py.
## Every character sprite in res://art/px/figures/: [cell size, feet anchor, drawn bounds relative to
## the feet], in art pixels (1x).

const CELLS := {
	"mamuthone_black_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-23, -69, 41, 70)],
	"mamuthone_black_crouch": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -65, 44, 66)],
	"mamuthone_black_air": [Vector2(88, 84), Vector2(44, 80), Rect2(-22, -70, 39, 70)],
	"mamuthone_black_land": [Vector2(88, 84), Vector2(44, 80), Rect2(-25, -64, 48, 65)],
	"mamuthone_dark_brown_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-23, -69, 41, 70)],
	"mamuthone_dark_brown_crouch": [Vector2(88, 84), Vector2(44, 80), Rect2(-24, -65, 44, 66)],
	"mamuthone_dark_brown_air": [Vector2(88, 84), Vector2(44, 80), Rect2(-22, -70, 39, 70)],
	"mamuthone_dark_brown_land": [Vector2(88, 84), Vector2(44, 80), Rect2(-25, -64, 48, 65)],
	"issohadore_stand": [Vector2(88, 84), Vector2(44, 80), Rect2(-14, -70, 30, 71)],
	"issohadore_throw": [Vector2(88, 84), Vector2(44, 80), Rect2(-14, -80, 29, 81)],
	"big_mamuthone_black_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-36, -110, 64, 110)],
	"big_mamuthone_black_crouch": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -103, 70, 103)],
	"big_mamuthone_black_air": [Vector2(140, 132), Vector2(70, 127), Rect2(-35, -111, 62, 110)],
	"big_mamuthone_black_land": [Vector2(140, 132), Vector2(70, 127), Rect2(-40, -102, 76, 102)],
	"big_mamuthone_dark_brown_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-36, -110, 64, 110)],
	"big_mamuthone_dark_brown_crouch": [Vector2(140, 132), Vector2(70, 127), Rect2(-38, -103, 70, 103)],
	"big_mamuthone_dark_brown_air": [Vector2(140, 132), Vector2(70, 127), Rect2(-35, -111, 62, 110)],
	"big_mamuthone_dark_brown_land": [Vector2(140, 132), Vector2(70, 127), Rect2(-40, -102, 76, 102)],
	"big_issohadore_stand": [Vector2(140, 132), Vector2(70, 127), Rect2(-22, -112, 47, 112)],
	"big_issohadore_throw": [Vector2(140, 132), Vector2(70, 127), Rect2(-22, -127, 44, 127)],
}
