class_name FireCells
extends RefCounted
## Generated by tools/art/fire_night/render.js — do not edit; re-run it after changing the art.
## Every Fire Night sprite in res://art/fire/: [cell size, anchor, drawn bounds relative to the anchor],
## all in the mockup's reference pixels (the PNGs are baked at a multiple of that).

const FIG_H := 300.0   ## figures are drawn this tall in their cells
const CELLS := {
	"sky": [Vector2(720.0, 260.0), Vector2(0.0, 195.0), Rect2(0.0, -195.0, 720.0, 260.0)],
	"ground": [Vector2(720.0, 1094.0), Vector2(0.0, 45.0), Rect2(0.0, -45.0, 720.0, 1094.0)],
	"pyre": [Vector2(400.0, 80.0), Vector2(200.0, 48.0), Rect2(-99.5, -29.0, 215.0, 38.5)],
	"setts": [Vector2(720.0, 208.0), Vector2(0.0, 0.0), Rect2(0.0, 0.0, 720.0, 208.0)],
	"gem": [Vector2(256.0, 250.0), Vector2(128.0, 62.0), Rect2(-78.0, -40.5, 156.0, 168.0)],
	"gem_call": [Vector2(256.0, 250.0), Vector2(128.0, 62.0), Rect2(-74.0, -31.5, 148.0, 131.0)],
	"hold_ring": [Vector2(160.0, 80.0), Vector2(80.0, 40.0), Rect2(-65.5, -30.0, 131.0, 60.0)],
	"sash": [Vector2(82.0, 64.0), Vector2(0.0, 0.0), Rect2(0.0, 0.0, 82.0, 64.0)],
	"bar_up": [Vector2(720.0, 90.0), Vector2(360.0, 45.0), Rect2(-360.0, -24.5, 720.0, 69.5)],
	"bar_down": [Vector2(720.0, 90.0), Vector2(360.0, 45.0), Rect2(-360.0, -24.5, 720.0, 69.5)],
	"badge": [Vector2(120.0, 104.0), Vector2(60.0, 52.0), Rect2(-40.5, -34.5, 81.0, 69.0)],
	"rope_r": [Vector2(720.0, 110.0), Vector2(360.0, 55.0), Rect2(-336.5, -35.0, 663.0, 70.0)],
	"rope_l": [Vector2(720.0, 110.0), Vector2(360.0, 55.0), Rect2(-326.5, -35.0, 663.0, 70.0)],
	"hatch": [Vector2(32.0, 32.0), Vector2(0.0, 0.0), Rect2(0.0, 0.0, 32.0, 32.0)],
	"button_idle": [Vector2(280.0, 236.0), Vector2(30.0, 30.0), Rect2(-3.5, -0.5, 227.0, 183.0)],
	"button_cued": [Vector2(280.0, 236.0), Vector2(30.0, 30.0), Rect2(-5.0, -5.0, 230.0, 186.0)],
	"button_pressed": [Vector2(280.0, 236.0), Vector2(30.0, 30.0), Rect2(-9.5, -9.5, 239.0, 195.0)],
	"button_hit": [Vector2(280.0, 236.0), Vector2(30.0, 30.0), Rect2(-9.5, -9.5, 239.0, 195.0)],
	"button_miss": [Vector2(280.0, 236.0), Vector2(30.0, 30.0), Rect2(-3.5, -0.5, 227.0, 183.0)],
	"foot_r": [Vector2(60.0, 100.0), Vector2(30.0, 50.0), Rect2(-13.5, -33.0, 26.0, 61.5)],
	"foot_l": [Vector2(60.0, 100.0), Vector2(30.0, 50.0), Rect2(-12.5, -33.0, 26.0, 61.5)],
	"mamuthone_black_a": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-112.0, -290.0, 191.0, 290.0)],
	"mamuthone_black_b": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-112.0, -305.0, 191.0, 290.0)],
	"mamuthone_dark_brown_a": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-112.0, -290.0, 191.0, 290.0)],
	"mamuthone_dark_brown_b": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-112.0, -305.0, 191.0, 290.0)],
	"issohadore": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-71.0, -376.0, 127.0, 376.0)],
	"mamuthone_black_a_r": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-79.0, -290.0, 191.0, 290.0)],
	"mamuthone_black_b_r": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-79.0, -305.0, 191.0, 290.0)],
	"mamuthone_dark_brown_a_r": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-79.0, -290.0, 191.0, 290.0)],
	"mamuthone_dark_brown_b_r": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-79.0, -305.0, 191.0, 290.0)],
	"issohadore_r": [Vector2(480.0, 480.0), Vector2(240.0, 450.0), Rect2(-56.0, -376.0, 127.0, 376.0)],
}
