class_name LookCells
extends RefCounted
## Generated by tools/art/pixel/workshop.py - do not edit; re-run it after figures.py changes.
## Where the player's own look goes on the shared Mamuthone figures, per "<size>_<pose>", in art
## pixels relative to the figure's feet (facing right).

const DIR := "res://art/px/workshop/"
## The carved mask's stamp in the figure (the player's mask is drawn over it).
const MASK := {
	"field_stand": Rect2i(-2, -61, 9, 14),
	"field_crouch": Rect2i(-2, -57, 9, 14),
	"field_air": Rect2i(-2, -62, 9, 14),
	"field_land": Rect2i(-2, -56, 9, 14),
	"big_stand": Rect2i(-4, -98, 14, 22),
	"big_crouch": Rect2i(-4, -91, 14, 22),
	"big_air": Rect2i(-4, -99, 14, 22),
	"big_land": Rect2i(-4, -90, 14, 22),
}
## Where the chest straps meet.
const YOKE := {
	"field_stand": Vector2(1.5, -42.0),
	"field_crouch": Vector2(1.5, -38.0),
	"field_air": Vector2(1.5, -43.0),
	"field_land": Vector2(1.5, -37.0),
	"big_stand": Vector2(2.0, -67.6),
	"big_crouch": Vector2(2.0, -60.6),
	"big_air": Vector2(2.0, -68.6),
	"big_land": Vector2(2.0, -59.6),
}
## Top-left of straps_dark_<key>.png (the straps recoloured dark leather).
const STRAPS := {
	"field_stand": Vector2i(-10, -52),
	"field_crouch": Vector2i(-11, -48),
	"field_air": Vector2i(-10, -53),
	"field_land": Vector2i(-12, -47),
	"big_stand": Vector2i(-16, -83),
	"big_crouch": Vector2i(-18, -76),
	"big_air": Vector2i(-16, -84),
	"big_land": Vector2i(-19, -75),
}
## Bell sprites bell_<size>.png: the point each hangs from.
const BELL_HANG := {
	"xs": Vector2i(3, 0),
	"s": Vector2i(4, 0),
	"m": Vector2i(5, 0),
	"l": Vector2i(6, 0),
	"xl": Vector2i(7, 0),
}
## Extra bells per bell set: [bell size, hang point relative to the yoke, "front" | "back"].
const BELLS := {
	"field": {"light": [], "village": [["s", Vector2(-8.0, 10.0), "front"], ["s", Vector2(0.0, 9.0), "front"], ["s", Vector2(8.0, 10.0), "front"]], "full": [["xs", Vector2(-12.0, 10.4), "front"], ["s", Vector2(-6.0, 9.7), "front"], ["m", Vector2(0.0, 9.0), "front"], ["s", Vector2(6.0, 9.7), "front"], ["xs", Vector2(12.0, 10.4), "front"], ["m", Vector2(11.0, -13.0), "back"], ["m", Vector2(15.5, -6.0), "back"], ["m", Vector2(17.5, 2.0), "back"]]},
	"big": {"light": [], "village": [["m", Vector2(-12.8, 15.9), "front"], ["m", Vector2(0.0, 14.4), "front"], ["m", Vector2(12.8, 15.9), "front"]], "full": [["s", Vector2(-19.2, 16.7), "front"], ["m", Vector2(-9.6, 15.6), "front"], ["l", Vector2(0.0, 14.4), "front"], ["m", Vector2(9.6, 15.6), "front"], ["s", Vector2(19.2, 16.7), "front"], ["l", Vector2(17.6, -20.8), "back"], ["l", Vector2(24.8, -9.6), "back"], ["l", Vector2(28.0, 3.2), "back"]]},
}
## The second chest strap the belt bells hang from, relative to the yoke.
const BELT := {
	"field": [Vector2(-14.0, 10.2), Vector2(14.0, 10.2)],
	"big": [Vector2(-22.4, 16.3), Vector2(22.4, 16.3)],
}
