class_name PixelPalette
extends RefCounted
## Generated by tools/art/pixel/gen_palette_gd.py from tools/art/pixel/palette.py - do not edit.
## The "Bonfire Night" pixel palette (docs/art-style.md): ramps dark to light, e.g. FIRE[5].

const K: Array[Color] = [Color("#07060e"), Color("#0e0d1a")]
const NIGHT: Array[Color] = [Color("#0a0c24"), Color("#10163a"), Color("#18204e"), Color("#222c62"), Color("#303a78"), Color("#434c8c")]
const HILL: Array[Color] = [Color("#141630"), Color("#1d2040"), Color("#2a2c50")]
const STAR: Array[Color] = [Color("#c9cde8"), Color("#f4f1dc")]
const FIRE: Array[Color] = [Color("#4a0a0c"), Color("#7c1812"), Color("#b8321a"), Color("#e2561a"), Color("#f47e22"), Color("#fbb23a"), Color("#fde07a"), Color("#fff6cf")]
const STONE: Array[Color] = [Color("#1c1418"), Color("#2c2026"), Color("#3e2e30"), Color("#58403a"), Color("#7a5842"), Color("#a07650"), Color("#c89a64")]
const SETT: Array[Color] = [Color("#15151f"), Color("#1d1d29"), Color("#262634"), Color("#302f3f"), Color("#3d3b4c"), Color("#4c4858")]
const GOLD: Array[Color] = [Color("#2e1c0c"), Color("#56340f"), Color("#8a5a1c"), Color("#c08a2e"), Color("#e8b64c"), Color("#f8dc8a")]
const RED: Array[Color] = [Color("#2e0608"), Color("#5c0c10"), Color("#8e1a18"), Color("#c02a22"), Color("#e24a32")]
const BONE: Array[Color] = [Color("#4e4540"), Color("#8a7c6c"), Color("#c4b494"), Color("#ecdfbc"), Color("#fdf6df")]
const FLEECE: Array[Color] = [Color("#0c0908"), Color("#171110"), Color("#231915"), Color("#33241c"), Color("#4a3424"), Color("#6a4a2e")]
const WOOD: Array[Color] = [Color("#140f0e"), Color("#241c19"), Color("#382c26"), Color("#544236"), Color("#7a624c")]
const LEATHER: Array[Color] = [Color("#2a150c"), Color("#4a2616"), Color("#6e3c20"), Color("#96582e")]
const ROPE: Array[Color] = [Color("#6e5a3e"), Color("#a88e62"), Color("#d8c294")]
const NAVY: Array[Color] = [Color("#0b0c1c"), Color("#12142a"), Color("#1a1d3a"), Color("#252a50")]
const MOSS: Array[Color] = [Color("#1a2216"), Color("#28331e"), Color("#3a4628")]
const SKIN: Array[Color] = [Color("#5a3a2e"), Color("#8a5e44"), Color("#c08a64")]

## Art pixels per base-screen pixel: art is authored at 240 x 480 for the 720 x 1440 base screen.
const PX := 3.0
