class_name SetupCells
extends RefCounted
## Generated by tools/art/pixel/setup_pics.py - do not edit.
const DIR := "res://art/px/setup/"
const TILTS: Array[float] = [-0.9, -0.675, -0.45, -0.225, 0.0, 0.225, 0.45, 0.675, 0.9]
const DRUM_FRAMES := 4
const HEADPHONES := Vector2i(128, 104)
const PHONE := Vector2i(136, 150)
const DRUM := Vector2i(132, 116)
const ARROW := Vector2i(64, 30)
## thumb_up / thumb_down: a thumb coming up from below, tip at the top centre.
const THUMB := Vector2i(16, 34)
